# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Think11 App"
client_id = "0c31a2582b51a56482e9ceb2f794a5dc"
application_url = "https://custom-price.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://custom-price.fly.dev/auth/callback",
  "https://custom-price.fly.dev/auth/shopify/callback",
  "https://custom-price.fly.dev/api/auth/callback",
  "https://custom-price.fly.dev/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ulwt.myshopify.com"
